rigs:
  -
    name: 'A'
    wells: ['w1', 'w2', 'w3', 'w4','w5', 'w6', 'w7', 'w8','w9', 'w10', 'w11', 'w12','w13']
    slots: ['S1', 'S2', 'S3','S4', 'S5', 'S6','S7', 'S8', 'S9','S10', 'S11', 'S12','S13', 'S14', 'S15']
  -
    name: 'B'
    wells: ['w1', 'w2', 'w3', 'w8','w9', 'w10', 'w11', 'w12','w13', 'w14', 'w15', 'w16','w17', 'w18', 'w19', 'w20']
    slots: ['S3','S4', 'S5', 'S6','S7', 'S8', 'S9','S10', 'S11', 'S12', 'S16','S17','S18']
  -
    name: 'C'
    wells: [ 'w4','w5', 'w6', 'w7', 'w8', 'w10', 'w11', 'w12','w13', 'w14', 'w15', 'w16','w17', 'w18']
    slots: ['S1', 'S2', 'S3','S4', 'S5', 'S6','S7', 'S11', 'S12','S13', 'S14', 'S15','S19','S20']
slots:
  -
    name: 'S1'
    wells: ['w1', 'w2', 'w3', 'w4','w5', 'w6', 'w7']
  -
    name: 'S2'
    wells: ['w1', 'w2', 'w3', 'w4','w5', 'w6', 'w7']
  -
    name: 'S3'
    wells: ['w1', 'w2', 'w3', 'w4','w5', 'w6', 'w7']
  -
    name: 'S4'
    wells: ['w1', 'w2', 'w3', 'w4','w5', 'w6', 'w7']
  -
    name: 'S5'
    wells: ['w1', 'w2', 'w3', 'w4','w5', 'w6', 'w7']
  -
    name: 'S6'
    wells: ['w5', 'w6', 'w7','w8','w9', 'w10']
  -
    name: 'S7'
    wells: ['w5', 'w6', 'w7','w8','w9', 'w10']
  -
    name: 'S8'
    wells: ['w5', 'w6', 'w7','w8','w9', 'w10']
  -
    name: 'S9'
    wells: ['w5', 'w6', 'w7','w8','w9', 'w10']
  -
    name: 'S10'
    wells: ['w5', 'w6', 'w7','w8','w9', 'w10']
  -
    name: 'S11'
    wells: ['w8','w9', 'w10','w11', 'w12','w13', 'w14', 'w15']
  -
    name: 'S12'
    wells: ['w8','w9', 'w10','w11', 'w12','w13', 'w14', 'w15']
  -
    name: 'S13'
    wells: ['w8','w9', 'w10','w11', 'w12','w13', 'w14', 'w15']
  -
    name: 'S14'
    wells: ['w8','w9', 'w10','w11', 'w12','w13', 'w14', 'w15','w16']
  -
    name: 'S15'
    wells: ['w8','w9', 'w10','w11', 'w12','w13', 'w14', 'w15','w16']
  -
    name: 'S16'
    wells: ['w8','w9', 'w10','w11', 'w12', 'w13', 'w14', 'w15','w16']
  -
    name: 'S17'
    wells: ['w12', 'w13', 'w14', 'w15','w17', 'w18', 'w19', 'w20']
  -
    name: 'S18'
    wells: ['w12', 'w13', 'w14', 'w15','w17', 'w18', 'w19', 'w20']
  -
    name: 'S19'
    wells: ['w12', 'w13', 'w14', 'w15','w17', 'w18', 'w19', 'w20']
  -
    name: 'S20'
    wells: ['w12', 'w13', 'w14', 'w15','w17', 'w18', 'w19', 'w20']